apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cosign
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-cli-1-0-beta/cosign@sha256:adabaddaebcba7b0134325e7bed5e94d08133cab65d7a183e4fd0ab860ab243d
        name: container-image
        resources: {}
status: {}
